In [ ]:
!pip install scikit-learn
!pip install pandas
!pip install openpyxl


   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpy

In [27]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

In [10]:
labels = pd.read_csv("../data/human/CRC_metadata.csv")

file_path = "../data/Priya_et_al_Supplementary_Tables/Supplementary Tables S12-S17.xlsx"

data = pd.read_excel(file_path, sheet_name=None)
data.keys()

dict_keys(['S12', 'S13', 'S14', 'S15', 'S16', 'S17'])

In [34]:
gene_data = data["S12"]
gene_data.head()

Unnamed: 0  B01  B02  B03  B04  B05  B06   B07  B08   B09  ...   s74   s85  \
0     TSPAN6  235  815  351  629   91  175  1240  600  1325  ...  1426  1230   
1       TNMD   23   15  188   12    4   10    24   11    13  ...    34    14   
2       DPM1  184  166  146  124  150  121   536  212   237  ...   299   345   
3      SCYL3  263  389  185  231  480  340   432  335   559  ...   546   267   
4   C1orf112   98   73   69   70  457  106   233  109   114  ...   289   198   

   s86  s87  s88   s89  s90   s94  s95  s96  
0  206  809  103  1028   14  1985  369  291  
1    7    0    6    46    0    16    3    7  
2  283  325  223   327   29   606  344  198  
3  298  529  250   416   91   428  493  287  
4  133  323  103   178   10   247  289  115  

[5 rows x 89 columns]

In [48]:
gene_data = gene_data.set_index('Unnamed: 0')
gene_data.head()

B01  B02  B03  B04  B05  B06   B07  B08   B09  B10  ...   s74  \
Unnamed: 0                                                      ...         
TSPAN6      235  815  351  629   91  175  1240  600  1325  672  ...  1426   
TNMD         23   15  188   12    4   10    24   11    13    8  ...    34   
DPM1        184  166  146  124  150  121   536  212   237  275  ...   299   
SCYL3       263  389  185  231  480  340   432  335   559  427  ...   546   
C1orf112     98   73   69   70  457  106   233  109   114  148  ...   289   

             s85  s86  s87  s88   s89  s90   s94  s95  s96  
Unnamed: 0                                                  
TSPAN6      1230  206  809  103  1028   14  1985  369  291  
TNMD          14    7    0    6    46    0    16    3    7  
DPM1         345  283  325  223   327   29   606  344  198  
SCYL3        267  298  529  250   416   91   428  493  287  
C1orf112     198  133  323  103   178   10   247  289  115  

[5 rows x 88 columns]

ValueError: could not convert string to float: 'TSPAN6'

T-Test:

In [26]:
from scipy.stats import ttest_ind


Unnamed: 0  B01  B02  B03  B04  B05  B06   B07  B08   B09  ...   s74   s85  \
0     TSPAN6  235  815  351  629   91  175  1240  600  1325  ...  1426  1230   
1       TNMD   23   15  188   12    4   10    24   11    13  ...    34    14   
2       DPM1  184  166  146  124  150  121   536  212   237  ...   299   345   
3      SCYL3  263  389  185  231  480  340   432  335   559  ...   546   267   
4   C1orf112   98   73   69   70  457  106   233  109   114  ...   289   198   

   s86  s87  s88   s89  s90   s94  s95  s96  
0  206  809  103  1028   14  1985  369  291  
1    7    0    6    46    0    16    3    7  
2  283  325  223   327   29   606  344  198  
3  298  529  250   416   91   428  493  287  
4  133  323  103   178   10   247  289  115  

[5 rows x 89 columns]

In [36]:
y = labels["Description"].map({"tumor": 1, "normal": 0}).to_numpy()
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0])

In [49]:
x = gene_data.to_numpy()
x = x[:,:]
x

array([[ 235,  815,  351, ..., 1985,  369,  291],
       [  23,   15,  188, ...,   16,    3,    7],
       [ 184,  166,  146, ...,  606,  344,  198],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    5, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]])

In [50]:
scaler = StandardScaler()
x = scaler.fit_transform(x)
x = pd.DataFrame(x, columns=gene_data.columns, index=gene_data.index)


In [ ]:


p_values = []
for gene in gene_data.columns:
    t_stat, p = ttest_ind(x[gene], x[gene], equal_var=False)
    p_values.append(p)

# Add p-values to a DataFrame
ttest_results = pd.DataFrame({
    "gene": x.columns,
    "p_value": p_values
}).set_index("gene")

In [53]:
ttest_results

p_value
gene         
B01       1.0
B02       1.0
B03       1.0
B04       1.0
B05       1.0
...       ...
s89       1.0
s90       1.0
s94       1.0
s95       1.0
s96       1.0

[88 rows x 1 columns]

In [57]:
# Fit LASSO with cross-validation
lasso = LogisticRegressionCV(
    penalty='l1', solver='saga', cv=5, max_iter=10000, random_state=42
)
lasso.fit(x.to_numpy().T, y)




LogisticRegressionCV(cv=5, max_iter=10000, penalty='l1', random_state=42,
                     solver='saga')

In [58]:
lasso.coef_[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [60]:
# Get coefficients
coef = pd.Series(lasso.coef_[0], gene_data.index)
selected_genes = coef[coef != 0]

In [61]:
selected_genes

Unnamed: 0
PDK4       -0.002375
CEACAM7    -0.004178
CLCA4      -0.050241
VCAN        0.013465
VMP1        0.147017
              ...   
HBB        -0.029149
MTRNR2L1   -0.002959
TXNIP      -0.013318
MYO15B     -0.040190
FCGBP      -0.113942
Length: 76, dtype: float64

In [62]:
selected_genes_sorted = selected_genes.sort_values(ascending=False)

selected_genes_sorted

Unnamed: 0
EEF1A1     0.392293
FLNA       0.288633
ITGA5      0.166996
MUC2       0.166017
MT-ND4     0.155480
             ...   
DST       -0.202774
AHNAK     -0.237468
LPP       -0.282125
MYLK      -0.322384
SLC26A3   -0.442460
Length: 76, dtype: float64

In [66]:
from sklearn.model_selection import train_test_split


In [67]:
X_train, X_test, y_train, y_test = train_test_split(
    x.to_numpy().T, y,
    test_size=0.2,        # 20% test data, 80% train
    random_state=42,      # ensures reproducibility
    stratify=y            # keeps class distribution balanced
)

In [74]:
X_train.shape

(70, 19264)

In [75]:
X_test.shape

(18, 19264)

In [68]:
lasso_predictor = LogisticRegressionCV(
    penalty='l1', solver='saga', cv=5, max_iter=10000, random_state=42
)
lasso_predictor.fit(X_train, y_train)


LogisticRegressionCV(cv=5, max_iter=10000, penalty='l1', random_state=42,
                     solver='saga')

In [ ]:
y_pred = lasso_predictor.predict(X_test)
y_proba = lasso_predictor.predict_proba(X_test)[:, 1]

In [71]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [72]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [73]:
y_proba

array([0.1274983 , 0.11047701, 0.06748544, 0.32026885, 0.14370237,
       0.98860383, 0.48962768, 0.82454113, 0.07866787, 0.99144146,
       0.81330758, 0.07955648, 0.99362327, 0.99775666, 0.95591475,
       0.96813018, 0.0115033 , 0.74110465])

In [76]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         9

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18

